services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpcservice:
    image: ${DOCKER_REGISTRY-}discountgrpcservice
    build:
      context: .
      dockerfile: Services/Discount/Discount.GrpcService/Dockerfile

volumes:
  postgres_catalog:  
    name: postgres_data

  postgres_basket:
    name: postgres_basket_data



